### ISSUE TITLE
Mural integration with GitHub

### ISSUE THREAD

**Issue by MoAdeyoju** [USEPA/easey-in#10]
Test how well Mural integrates with GitHub and what capabilities/advantages this offers

**Comment by davidkwartler** [comment]
https://www.mural.co/new-features/github-integration

**Comment by davidkwartler** [comment]
Mural also integrates with Jira, allowing us to create issues from Mural sticky notes
https://support.mural.co/en/articles/2113733-installing-the-jira-integration

**Comment by davidkwartler** [comment]
[Mural Integrations - EPA CAMD - v1.0.pdf](https://github.com/USEPA/easey-in/files/4938691/Mural.Integrations.-.EPA.CAMD.-.v1.0.pdf)
